// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5SEMoXJoP7xZ6SRKHjOr6y8IEHyLIYZk',
    appId: '1:765340489105:web:8d612918656e16c5363630',
    messagingSenderId: '765340489105',
    projectId: 'asynchronous-tugas',
    authDomain: 'asynchronous-tugas.firebaseapp.com',
    storageBucket: 'asynchronous-tugas.firebasestorage.app',
    measurementId: 'G-HWTP1ZS5CV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD37DCtdXDrbTEKgibeMTX6ZTbhI-Ed6HM',
    appId: '1:765340489105:android:f9a954ba104092c8363630',
    messagingSenderId: '765340489105',
    projectId: 'asynchronous-tugas',
    storageBucket: 'asynchronous-tugas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaZbGCoVFUbd7xTmSPOy7vdEtit9Rr8mU',
    appId: '1:765340489105:ios:33774c6a65df5c33363630',
    messagingSenderId: '765340489105',
    projectId: 'asynchronous-tugas',
    storageBucket: 'asynchronous-tugas.firebasestorage.app',
    iosBundleId: 'com.example.asynchronous',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaZbGCoVFUbd7xTmSPOy7vdEtit9Rr8mU',
    appId: '1:765340489105:ios:33774c6a65df5c33363630',
    messagingSenderId: '765340489105',
    projectId: 'asynchronous-tugas',
    storageBucket: 'asynchronous-tugas.firebasestorage.app',
    iosBundleId: 'com.example.asynchronous',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5SEMoXJoP7xZ6SRKHjOr6y8IEHyLIYZk',
    appId: '1:765340489105:web:f02445d8426a4696363630',
    messagingSenderId: '765340489105',
    projectId: 'asynchronous-tugas',
    authDomain: 'asynchronous-tugas.firebaseapp.com',
    storageBucket: 'asynchronous-tugas.firebasestorage.app',
    measurementId: 'G-LY932TVKT2',
  );
}
